---
title: "이해관계자"
description: |
  이해관계에 관하여
author:
  - name: sonsungman
    url: https://sonsungman.github.io/SKKU-Preditive.m/
date: 10-17-2021
output:
  distill::distill_article
---

### 고찰

계리사의 업무는 다양한 이해관계자가 얽혀있는 문제에 있어 해결책을 제시하는 것이다. 모든 문제는 다양한 이해관계가 반영되어 있다. 각각의 이해관계자는 자신의 입장이 존재한다. 그들이 추구하는 가치를 명확하게 아는 것이 문제 해결의 출발점이다. 이는 권력의 핵심과도 일맥상통하다. 권력, 혹은 영향력은 상대방이 추구하는 가치를 명확하게 이해하고 상대방이 원하는 것을 주는 것과 동일하다. 돈, 명예, 자신의 자리, 취업, 주색등 개인의 차원을 넘어서 조직의 법적 다툼에 대한 법적 승리, 정치적 영향력 상승 등. 

### 해결책

혹자는 상대와의 대화를 통해 상대의 생각 바탕의 가치를 읽어 내라 말한다. 혹자는 비즈니스적 마인드, 윈윈하는 파이나누기 식의 아이디어를 말한다. 혹자는 가치를 이야기한다. 보수 혹은 진보의 전통적 가치와 같은 것들. 옳다. 하지만 나는 앞서 언급한 사고 방식의 밑바탕에는 전형적인 서양식 사고틀이 자리잡고 있다 생각한다. 서양식 사고틀. 우리는 또다른 사고의 틀이 필요하다. 서양외에 어디에 있는가? 동양의 사고가 있다. 한국의 사고방식은 필히 서양에 뿌리 두고 있다 생각한다. 50년대 이후 국내의 대학강단은 대부분 서양에서 교육을 받은 선생님들이 학생들을 가르쳐왔다 생각한다. 우리가 다른 방식으로 문제를 바라보고자 한다면 우리는 동양식의 사고가 필요하다. 효용성에 관한 문제이다. 서양식 사고를 깊숙하게 훈련받은 사람들은 동양식 사고를 하는 사람들을 이해하지 못한다. 특히 계리사들은 전형적인 서양적 사고방식의 틀에 기초를 세운 학문에서 학습한 것. 복합적 사고가 필요하다. 이는 우리가 직면하는 문제의 복잡성에 기인한다. 생각의 뿌리, 우리가 받은 교육의 뿌리, 기틀을 깊이 생각할 필요가 있다. 깊은 고민이 필요한 시점이다.

