---
title: "Loss models"
description: |
  Loss models Abstract 
author:
  - name: sonsungman
    url: https://sonsungman.github.io/SKKU-Preditive.m
date: 03-09-2021
output:
  distill::distill_article
---


## Abstract


### 1



Loss Models 라는 책 제목부터 생각해보자. Loss는 무엇인가? 자동차 사고가 났다고 상상해보자. 당신의 소중한 차 뒷 범퍼를 누군가 쳤다. 가해자는 내려서 연신 죄송하다 할 것이고 당신은 뒷목을…. 아니 차 상태를 확인하고 보험 처리를 할 것이다. 여기에서 뒷 범퍼 수리비가 loss가 된다. 물론 당신이 입은 허리 통증에 대한 치료비 또한 loss가 될 수 있다. 또 다른 예로 집에 불이 났다고 해보자. 집이 홀랑 다 타버렸다. 다행히도 당신의 집은 화재보험에 가입한 상태이기에 주택 전손에 대한 보험금을 보험사로부터 청구할 것이다. 여기에서 보험사의 담보에 따라 다르겠지만 화재로 손실된 주택의 가격이 곧 loss이다. 그러면 Models은 무엇인가? 현실 혹은 실제에 대한 모형을 의미한다. Loss model은 손해에 대한 모형이다. 그렇다면 손해에 대한 모형을 다루는 책이 loss models가 된다. 왜 손해에 대한 모형이 필요할까?


### 2


그에 대한 답이 파트 1인 INTRODUCTION에서 나온다. 계리학에서의 많은 문제들은 미래의 insurance cost를 예측하는데 사용될 수 있는 수학적 모델을 구축하는 것을 포함한다. 다시 말하면 loss에 대한 모델을 만들어 보험사가 미래에 당신의 뒷 범퍼 수리비(loss, 보험사 입장에선 cost)를 얼마나 지급해야 할지를 예측할 수 있다. 또한 그 예측을 바탕으로 보험사는 차 사고범에게 받을 보험료도 고려할 것이다. (보험요율 산정이나 준비금 적립에 관한 사항은 Loss Models의 범위를 벗어나기에 다른 서적을 참고하기 바란다.)


### 3


Loss와 모델에 대한 의미가 어느정도 이해되었을 것이라 생각된다. 파트 1을 넘어서 파트 2로 이동해보자. 파트 2 에서는 계리적 상황을 모델링하기위한 기본적인 확률 모델들을 다룬다. 여기에서 연속형 모델과 이산형 모델, 그리고 파라미터라는 개념이 등장하는데, 먼저 연속형 모델에는 다들 잘 알고 계시는 분포들이 등장한다. 정규, 지수, 감마, 파레토 등등의 분포가 등장하며 이 분포들은 손해액(loss)의 확률변수를 모델링하는데 사용될 수 있다. 마찬가지로 이산형 모델들 또한 등장한다. 이항, 포아송, 음이항 분포와 더불어 (a, b, 0) class, (a, b, 1) class 라는 개념들이 등장하고 Compound 된 빈도 분포들이 이야기된다. 이 이산형 분포들은 사건의 발생 횟수의 확률변수를 모델링하는데 사용될 수 있다. 미래에 보험사고가 몇 건이 발생할지 그리고 발생하게 된다면 얼마의 손해가 발생하게 될지를 연속형 분포와 이산형 분포를 통해 모델링하는 것이다. 이것을 통합적으로 생각하게 해주는 모델이 바로 책 9장에 등장하는 총손실모형 (Aggregate Loss Model)이다. 분포에 대한 설명은 이정도로 마치고 파라미터라는 개념을 알아보고 파트 3으로 넘어가보자.


### 4


파라미터란 무엇인가? 우리 말로는 모수라고 하는데, 모수는 우리가 관심있는 대상 즉, 모집단의 특성을 간략하게 함축하는 있는 개념이다. 앞서서 이야기한 연속형 분포와 이산형 분포는 모두 parametric distribution이다. 간단하게 말하면 이 몇 가지 모수들이 결정되기만 하면 전체 분포의 특성이 특징지어진다고 생각할 수 있다. 정규 분포의 예를 들어보면 정규 분포의 모습은 모수인 μ,σ의 결정만으로 확정된다. 그렇다면 이 모수들은 실제로 어떻게 구하는가? 차 뒷범퍼 수리비에 대한 모델링을 위해서 A손해보험사의 보험계리사 성균관씨가 이 문제를 고민하고 있다고 상상해보자. 자동차 사고에 대한 예상 손해액의 모델링을 하라는 지시가 내려왔고 성균관씨는 Loss Models에서 배웠던 내용을 상기하며 자동차 사고에 대한 예상 손해액에 적합한 분포를 파레토 분포라 확정 지였고 (models selection에 관한 방법론은 15장에 나온다) 파레토 분포의 모수 α,θ를 결정하려 하고 있다. 이 모수들에 따라 파레토 분포가 달라진다는 사실은 앞서 언급하였다. 이 모수들의 값을 결정하기 위해 성균관씨에게 필요한 것은 실제 자동차 사고 손해액 데이터이다. 이 실제 데이터를 통해 파레토 분포의 모수를 결정하므로 확정된 파레토 분포가 실제 현실과 잘 부합하도록 만드는 작업이 이루어진다. 이렇게 데이터를 통해 모수를 구하는(추정하는) 방법론은 수리통계학의 분야이며 Loss Models의 파트 3은 이러한 수리통계학을 다루고 있다.


### 5


자연스럽게 파트 3 수리통계학으로 넘어가보자. 점 추정, 구간 추정, 가설 검정에 대한 이론이 등장한다. 계리사들이 왜 통계학을 배워야 하는지 한편 통계학 전공자와 계리학 전공자의 차이 또한 드러나는 단원이다. 깊은 내용은 수업을 통해 들으실 수 있고 간략히 정리하면 앞서 말한 모델의 모수 추정은 MLE를 통해 이루어지게 된다. 그 외에도 적률추정법 혹은 퍼센타일 매칭 기법이 있기도 하다. 수리통계학의 마지막 단원은 13장 베이지안 추정 단원으로 몹시도 흥미로운 단원이다. 사전 분포와 사후 분포, 모델 분포의 용어와 관계에 익숙해지게 될 것이며 무엇보다 파트 5의 신뢰도 이론에서 베이지안 신뢰도와 문법을 공유하기에 베이지안 통계의 아이디어를 깊이 이해하는 것은 몹시 필요하고도 재미있는 일이다. 이해를 돕기 위해 하나의 예시를 들고 이 단원을 마무리하겠다. 앞서 계리사로 등장했던 성균관씨는 대학원 시절 계리학을 전공하였고 열심히 수업에 참여하며 동시에 계리사 자격증을 취득하기 위해 열심히 공부하였다고 상상해보자. 성균관씨의 동료 대학원생은 처음 성균관씨를 만났을 때에 성균관씨의 계리사 시험 합격률을 0.4로 판단했다고 한다. 하지만 성균관씨와 학기 수업을 진행해가며 성균관씨를 관찰한 결과 성균관씨의 학업 성실성을 바탕으로 성균관씨의 계리사 시험 합격률을 0.7로 판단하게 되었다 라고 해보자. 베이지안의 아이디어는 관찰 혹은 경험을 바탕으로 고정된 특정 대상의 성질(합격률)에 대한 판단을 바꾸어 가는 과정으로 볼 수 있다. 즉, 학기 수업을 진행해가며 성균관씨에 대한 합격률을 상향 조정하게 된 것은 성균관씨에 대한 관찰을 바탕으로 이루어진 것이다. 간략한 설명이 되었을 것이라고 생각하며 좀 더 깊은 수학적 모델은 Loss Models 교과서를 직접 참고하기 바란다.


### 6


이제 파트 3을 지나 파트 4로 넘어가보자. 파트 4는 경험적 모델의 구축과 모델 선택 방식을 이야기한다. 경험적 모델은 모수적 모델처럼 간단하게 소수의 모수로 설명할 수 없는 모델로 데이터 의존적 모델의 한 종류라고 이해하면 될 것 같다. (데이터 의존적 모델의 설명은 Loss Models를 참고하기 바란다.) 모수적 모델은 앞서 설명했듯이 몇 개의 모수들이 결정됨을 통해 모델의 모형이 확정되는 모델을 말했다. 그러면 경험적 모델은 무엇일까? Empirical model의 정의는 실제 데이터의 각각의 포인트에 1/n의 확률을 주는 모델을 말한다. 여기에서 n은 데이터의 개수를 말한다. 파트 4의 서두에도 나오지만 Empirical model은 기본적으로 “생존 분석” 이라는 분야에서 주로 연구되는 부분이다. 그럼에도 Lifetime을 모델링 하는 것에서 발생하는 문제들이 payments amount를 모델링 할 때에도 비슷하게 발생될 수 있어 경험적 모델이 loss models의 14장에 포함된 것이다. 이 단원에서 주의 깊게 봐야할 개념은 Kaplan–Meier와 Nelson–Aalen estimator이다. 재미있는 사실은 4판과 5판의 차이가 이 부분에서 나타나는데 Kaplan–Meier estimator를 구할 때에 요소가 MLE라는 것이 4판에서는 증명이 안되어 있는데 5판에는 증명이 간략하게 주어져 있다.


### 7


파트 4의 경험적 모델 부분이 끝나면 15장 모델 선택 단원이 나온다. 주어진 데이터에 어떠한 모델을 선택하여 모델링을 진행하는 것이 주어진 데이터를 잘 보여줄 수 있는지에 대해 논하며 검증 방법과 원칙에 대한 설명이 이루어진다. 잘 알려진 likelihood-ratio 검정, chi-square 검정, Kolmogorv-Smirnov 검정 등등의 정의와 쓰임새가 나오고 Judgment-Based Approaches, Score-Based Approaches 라는 두 가지 접근 방식을 논한다. 자세한 내용은 직접 Loss Models의 15단원을 읽어 나가시길 추천한다.


### 8


파트 5는 신뢰도 이론을 다룬다. 하나의 예시를 들어 설명을 이어가겠다. 앞서 A손해보험사의 성균관씨는 자동차 예상 손해액 모델링 프로젝트를 성공리에 마친 후 점심 식사 중 실손의료보험 상품 관련 업무를 담당하시는 선배 계리사로부터 이와 같은 푸념 섞인 농담을 듣게 된다. “아, 나일롱 환자들이 너무 많아서 그런 걸까? 아니면 감독원이 비급여 관리 방안에 대한 적절한 대안이 없어서 그런건지 원… 실손에서 손해가 계속되는데 우리 쪽에서는 손쓸 방도가 없네.” 이 말을 듣던 성균관씨는 씨익 웃으며 선배 계리사에게 “베이지안 아니 뷜만 신뢰도로 접근하면 되는 거 아닌가요?” 라고 의기양양하게 한 마디 하였지만 선배 계리사는 씨익 웃기만 할 뿐 말이 없었다. 이 예시에서 성균관씨가 말한 뷜만 신뢰도는 고전적 신뢰도, 베이지안 신뢰도와 함께 신뢰도 이론에 포함된다. 실손의료보험의 문제를 해결하기 위해 신뢰도 혹은 베이지안을 고려한다는 의미는 간단히 말해 환자의 실손보험료 결정 시 환자의 과거 경험 데이터를 사용하여 보험료를 조정하는 것을 의미한다. 즉, 과거에 많이 이용한 환자의 경우 그 경험 데이터를 반영하여 더 높은 실손보험료를 납부하도록 하는 식의 시스템을 고려하여 의료 과다이용으로 인한 회사의 손해가 줄어들도록 조치를 취하겠다는 의미인 것이다. 여기에서 조금 더 이론적으로 들어가 보면 고전적 신뢰도(최소 자승 신뢰도)는 데이터의 양 만을 고려하여 Z(신뢰도 계수)를 구해 조정하는 것이고 뷜만 신뢰도는 데이터의 양과 질 모두를 고려하여 요율 결정에 반영하는 것이다. 더 자세한 수학적 모델은 책을 참고하시면 될 것이다. 


### 9


이제 마지막 단원인 파트 6을 이야기해보고 이 글을 마무리하고자 한다. 파트 6은 시뮬레이션 단원이다. 난수 추출법과 부스트랩 방법, 실제로 Var이나 CTE 시뮬레이션 등의 이론이 전개된다. 이 단원은 특히 소프트웨어를 이용한 실습이 이루어 져야 한다. R을 이용하거나 엑셀을 사용하여 실제로 책 속의 알고리듬을 직접 시뮬레이션 해보는 좋은 기회가 될 것이다. Loss Models에 대한 간략한 요약이 이로서 완료되었다. 직접 Loss Models를 읽어보므로 말씀드린 내용들을 음미해 보기를 바라며 앞서서 이야기했지만 소프트웨어를 통한 실습이 반드시 이루어져야 한다. (끝)