---
title: "IAD part 1"
description: |
  From Lecture, Insurance Accounting and Discount rate
author:
  - name: sonsungman
    url: https://sonsungman.github.io/SKKU-Preditive.m
date: 04-02-2021
output:
  distill::distill_article

---


### 전체적 구조: IAA의 Discount rate 모노그래프를 통한 할인률의 이해
### 발표자료: Section II. 할인 시 목적과 목표- 이해관계자의 관점 설명 슬라이드 이후


#### 도입: 월간 보험 통계를 이용한 손해보험회사의 준비금 현황 확인



학생: 손해보험협회 월간 보험 통계에 들어가서 교수님께서 말씀하신 데이터를 찾아보았다.
손해보험협회에 등록되어 있는 손해보험회사들 목록이 나오고 종목별로 수입보험료 현황이 월별로 표시되어 있습니다. 교수님께서 말씀하신 대로 장기 상품이 다른 상품들에 비해 훨씬 수입 보험료 현황이 크고 파일을 받아서 엑셀로 열어 보았는데 장기 퍼센트를 계산해보았는데 대부분이 60%이상이며 80% 이상하는 회사들도 굉장히 많이 있다는 것을 알 수 있었다. 

교수님: 여러분이 보험회사를 가려고 하면서 보험회사를 모른다. 보험료수입에 대한 통계자료 맞나요? 보험료 수입이 이러한 통계를 보이면 준비금은 어떤 식일까요? 상상을 해보자. 

일동: 장기상품의 경우 준비금 금액이 휠씬 더 클 것 같습니다. 



#### 본론 1: IFRS17의 도입에 따른 손보사에 비해 생보사가 어려움에 직면한 이유



사고가 발생한 경우만 지급준비금으로 쌓여 있게 될 것이다. 장기 상품의 경우 보험료 들어온 것과 준비금과 비슷하다. 미경과 보험료 이런 것 이기 때문이다. 사고 난 것은 장기의 경우 지급 비금으로 쌓인다. 돈의 흐름을 재무제표를 보고 이해할 수 있어야 한다. 장기로 가면 준비금이 많고 IFRS17의 경우 손보사는 부담이 적다. 그렇다면 기간이 문제는 아닌 듯하다. IFRS17의 경우 무엇이 부담을 주는가? 보험상품에 이자율이 어떻게 부리되는가를 생각해야한다. 생명보험상품의 속성과 손해보험회사의 상품의 속성을 이해해야한다. 분자의 현금흐름을 만드는 곳과 분모의 할인율에 모두 이자율이 사용된다. 현금흐름을 만드는데 쓰이는 이자율과 할인에 쓰이는 이자율의 속성이 같은가? 지금 우리는 무엇을 하는가? 부채평가를 한다. 즉, 상품계약시에 계약자에게 제공하는 현금흐름에 적용되는 부리이율과 그 전체 현금흐름을 할인하는 할인율이 존재한다. 부리이율과 할인율과는 관계없다. 부리이율은 상품계약과 관련된 이율이다. 과거의 경우 부리이율이 확정 이율이 많이 존재했다. 점점 확정형 부리이율이 아닌 변동 이율을 적용되었고 그것이 시중에 공시된다고 하여 공시이율이라고 하였다. 그러므로 과거의 확정형 상품에서 변동형 상품으로 전환이 많이 되었다는 것을 알 수 있다. IFRS17의 도입에 따라 생명보험회사가 어려움에 처한 것은 결국 과거에 높은 확정 이율로 판매한 상품이 많기 때문이다. 지금은 고객 보호를 고민하기 보다 보험회사의 재무건전성을 고민해야 할 때이다. 



#### 본론 2: 공시이율과 할인율, 위험률, 해약율 결정의 중요성



손해보험사의 경우 장기 상품이 높은 비율로 금리연동형 상품이다. 이유는 장기 보험을 판매한 것이 오래된 일이 아니기 때문이다. 장기보험의 경우 생명보험에 비해서 만기가 짧다. 옛날의 확정형 계약들은 장기의 경우 상대적으로 짧은 만기로 계약이 종료되었다. 보험부채 평가시에 분자의 현금흐름을 프로젝션하여 할인율을 사용해 할인해서 현재가치를 측정한다. 할인율만 잘 정한 것으로 충분치 않고 분자의 부리이율과 여러 가지 위험율의 결정도 또한 몹시 중요하다. 분자에 들어갈 공시이율 모델링의 문제가 존재하고 각종 위험율과 해약율을 결정하는 것이 할인율 결정만큼 중요하다는 것을 인지해야만 한다. 부채평가에 있어서 분자와 분모 즉, 현금흐름과 할인율 측면에서 고려되야 할 것이 많이 때문에 복잡한 모델을 사용하는 것은 지양해야 한다. 전문가로서 합당하게 제시할 수 있어야 한다. 최근에 보험학회에서 저는 보험회사들의 공시이율 결정 매커니즘을 밝히고 부채평가시 공시이율 모델링이 간단해도 된다는 것을 이야기했다. 



#### 본론 3: 최저보증이율 – 할인율 공부의 필요성에 대하여



과거 금융감독원은 금리연동형 상품에 최저보증이율을 적용하라고 지시하였다. 만약 계산한 공시이율이 최저보증이율보다 낮을 경우 고객에게 최저보증이율을 부리이율로 적용해야만 한다는 의미이다. 앞선 경우 최저보증이율이 적용됨에 따라 자산이익율이 감소하고 공시이율 모델에 있어 자산이익율의 감소는 공시이율의 감소를 가지고와 결국 최저보증이율로 수렴하여 금리연동형 상품이 실상 금리확정형 상품이 되어버린다. 금리확정형 상품의 문제는 프로젝션된 현금흐름을 나타내는 분자는 상수가 되어버려 분모인 할인율이 변동에 따라 부채평가액이 심하게 변동되기 때문에 문제가 된다. 물론 이 부분은 준비금 평가에 있어 문제가 되는 부분이다. 손익측면에 있어서 문제가 되는 것은 버는 돈에 비해 더 많은 돈이 나가게 된다는 것이다. 자산이익율의 감소로 야기된다. 예를 들어 금리 10%로 팔았는데 자산이익율 6%라면 금리 역마진으로 보험사는 손해를 보게 된다. 결론적으로 부채 평가에 있어서 핵심적 원인은 금리확정으로 인해 분자와 분모가 같이 움직이지 못하기 때문이다. 금리연동형 상품을 많이 판매하여 보험사들의 손익이 많이 좋아졌다. 그럼에도 최저보증이율로인해 앞서 언급한 바와 같이 금리확정형으로 변화될 위험이 있고 보험부채의 변동성이 존재하게 된다. (분자와 분모가 함께 바뀌면 즉, 공시이율과 할인율이 외부 충격에 따라 같은 방향으로 움직여 보험부채의 변동성은 줄어든다.) 할인율 공부의 이유가 충분히 설명되었을 것이다. 



#### 본론 4: 할인율 선택 시 이해관계자의 관점을 고려, 위험 조정에 대하여, 주인과 대리인 문제(정보에 대하여)



이해관계자의 관점은 할인율 선택 시 고려되야 한다. 규제당국은 지급여력에 관심을 가질 경우, 할인율에 위험조정을 반영한다. 여기에서 위험조정은 비율로서 표현된 것이며 IFRS17상 위험조정은 준비금의 변동폭으로서 금액에 해당한다. (옮긴이-일반보험의 예를 들면 신뢰구간을 75%로 할 경우 확률론적 방법에 의해 미지급 손해액 추정액을 현 시점 지급된 것을 빼 그 총량 결과의 예측 분포를 생성하여 75%에서 mean을 뺀 것을 RA로 측정한다.) IFRS17의 RA는 주주에게 돌아가야 할 부분이다. 외부감사인의 경우 공정가치표시에 관심을 가질 경우, 외부적으로 관찰 가능한 요소를 고려하여 할인율을 선택한다. 최종적으로 보험회사의 할인율을 선택하는 보험계리사의 경우 앞서 말한 이해관계자들의 관점을 고려하여 할인율을 선택한다. 보험회사를 둘러싼 이해관계자들 예를 들어 규제당국은 규제를 만들고 주주들은 투자 금액을 회수하거나 추가하므로 계약자들은 계약을 해지하거나 유지하여 보험회사가 소위 엉뚱한 행동을 못하도록 한다. 즉, 의사결정이 제한된다. 주주와 대리인 문제에 있어 이해관계자들 보다 더 나은 대리인의 최대 장점은 정보다. 대리인은 정보를 가지고 자기 나름의 의사결정을 진행한다. 이해관계자의 경우 공시된 자료만 갖는다 규제당국조차 생각보다 적은 정보를 갖게 된다. 그러므로 대리인의 의사결정이 자신의 이익을 위함인지 주주에게 봉사하기 위함인지 알 수 없다. 대리인 문제는 결국 정보비대칭의 문제이다. 그러한 문제를 해결하기위해 여러가지 견제 장치들이 존재한다.


