---
title: "EMH"
description: |
  EMH에 대하여 
author:
  - name: sonsungman
    url: https://sonsungman.github.io/SKKU-Preditive.m
date: 03-08-2021
output:
  distill::distill_article

---


### Introduction


보험회사는 보험계약자와 보험계약을 맺고 일정 기간동안 특정 보험사고에 대한 보상을 제공하며 그에 대한 대가로서 보험료(Premium)을 받는다. 수많은 계약자로부터 납입된 보험료는 미래의 보험사고 발생에 대한 보상액 지불, 보험회사 운용에 대한 사업비 지출 등에 쓰인다. 보험료 납입으로부터 시작된 현금흐름의 유입과 보상액, 사업비 지출로 인한 현금흐름의 유출 사이에는 시간적 차가 존재하므로 보험회사는 유입된 보험료를 바탕으로 투자활동에 나서게 되고 적정한 유동성을 유지하며 영업활동을 지속해 나간다. 그렇기에 보험회사의 재무상태표(B/S)의 자산 항목을 보면 투자된 채권과 주식의 규모를 볼 수 있다. 즉, 보험회사는 기관투자자로서 자본시장에 참여한다. 한편, 보험회사는 영업활동의 지속과 인수 위험(Risk)에 따른 버퍼(Buffer)로서 충분한 자본을 확보하고 있어야 하기에 필요시 자본시장으로부터 자본을 조달해야 하는 자금수요자로서 자본시장에 참여한다. 그러므로 자본시장을 이해해야 할 필요가 있으며 Fama(1970) 가 제시한 효율적 시장 가설에 대해 알아보도록 하자.


### 1


만약 과거 주가 시계열 자료를 분석하여 주가에 대한 예측모형이 발견되었다고 해보자. 이 예측 모형을 사용하여 현재 100인 X기업의 주가가 3일후에 200으로 상승할 것이라는 예측을 아는 투자자들은 모두 X기업의 주식을 매수하려 시도하고 이미 X기업의 주식을 보유한 투자자들은 매도하지 않는다. 이는 즉시 X기업의 주가가 200으로 상승하는 결과로 이어진다.


### 2


미래 성과에 대한 긍정적인 예측은 즉시 현재의 긍정적인 성과로 이어진다고 볼 수 있다. 더욱 일반적으로 말하면 주식의 성과 예측에 사용될 수 있는 어떠한 정보라도 주가에 이미 반영되어 있어야 한다. 현재 시점에서 이용가능한 모든 정보를 주가가 반영하고 있다면 주가는 예측 불가능한, 새로운 정보에만 변동해야 한다. 또한 주가가 예측 불가능한 정보에 변동하므로 주가 변동도 예측 불가능하다. 이것이 주가가 랜덤워크(Random Walk)를 따른다는 의미이다. 무작위적으로 움직이는 주가는 시장의 비합리성을 표현하는 것이 아니라 다른 투자자들 보다 먼저 정보를 얻으려 경쟁하는 투자자들로 인한 필연적인 결과이다. 다시 말하면 이용 가능한 모든 정보를 주가가 반영하고 있기에 랜덤워크는 그에 따른 자연스러운 결과가 되고 만약 실제로 주가의 움직임이 예측 가능하다면 이용 가능한 정보가 모두 주가에 반영되지 않았다는 의미이며 시장의 비효율성을 나타낸다. 그렇기에 현재 이용 가능한 모든 정보를 주가가 반영하고 있다는 개념을 효율적 시장 가설(Efficient Market Hypothesis)라 부른다.


### 3


효율적 시장 가설(EMH)은 세 가지의 유형으로 구분한다. 이 세 가지 유형은 모든 이용 가능한 정보의 의미에 따라 나뉜다. 약형 EMH는 모든 과거 정보가 주가에 반영되어 있음을 의미한다. 이는 과거 주가 추세를 분석하는 등의 기술적 분석(ex 차트 분석)을 통해서는 비정상적 수익을 얻을 수 없음을 말한다. 준강형 EMH는 현재 공시되거나 공개된 모든 정보가 주가에 반영되어 있음을 의미한다. 따라서 과거정보와 현재 공시 정보를 분석하는 기본적 분석(ex 재무 분석)으로는 비정상적 수익을 얻을 수 없음을 말한다. 강형 EMH는 현재 공개된 정보뿐 아니라 공개되지 않은 내부정보까지도 주가에 모두 반영되어 있음을 의미한다. 그렇기에 내부 정보를 가진 내부자들도 비정상수익을 얻을 수 없음을 말한다.


### 4


그렇다면 효율적 시장의 개념에도 불구하고 워렌 버핏, 피터 린치, 존 템플턴 등과 같은 투자업계의 슈퍼 스타들의 정상 수익률을 뛰어 넘는 탁월한 성과는 무엇인가? 이는 시장은 충분히 경쟁적이기  때문에 차별화될 만큼의 우월한 정보력이나 통찰력만이 그에 걸 맞는 보상을 받게 된다는 의미로 볼 수 있다. 다시 말하면 시장은 일반적으로 매우 효율적이지만 특별한 근면함, 지성, 창조성에 대한 보상이 여전히 기다리고 있다.


### 5


보험회사는 자본시장에서 자금공급자이자 자금수요자에 해당한다. 자금공급자로서 적절한 금융자산에 투자하여 투자 수익을 얻으려 하고 자금수요자로서 추가적인 주식 혹은 채권 발행을 통해 필요한 자금을 자본시장으로부터 조달한다. 효율적 시장 가설은 자본시장의 3가지 효율성 중 하나인 정보 효율성에 대한 이론으로서 자본시장의 참여자인 보험회사에게 투자한 증권과 자본시장에 대한 기본적 이해와 더불어 자금 조달을 위한 재무적 의사결정에 대한 밑바탕을 제공한다.


### 6


“나는 이제 증권분석의 정교한 기술이 가치 있는 주식을 찾아낼 수 있다고 주장하지 않는다 … (중략) … 옛날엔 유능한 증권 애널리스트라면 정밀한 분석을 통해 저평가 주식을 찾아내는 것이 가능하였다. 그러나 오늘날엔 많은 조사와 분석이 행해지고 있고, 이러한 노력에 대한 비용을 정당화하는 우월한 수익을 창출할 수 있을지 의문스럽다. 이와 같은 매우 제한적인 범위에서 나는 현재 교수들에 의해 지지 되고 있는 ‘효율적 시장 가설’에 동의한다” -Benjamin Graham- (INVESTMENTS, Zvi Bodie, 11th, 642p)


1976년 세미나에서의 Graham의 말이다. 그레이엄은 20세기 후반 현대 포트폴리오 이론(MPT)가 탄생하기 전까지 증권 분석 분야의 유일하고 몹시 중요한 사상가이자 저자였다. 그의 저서로는 <현명한 투자자>, <증권 분석> 등 투자업계의 스테디 셀러가 있으며 기본적 분석(Fundamental Security Analysis)를 그의 아이디어 없이는 논의할 수 없다. 가치 투자(Value Investing)의 아버지로서 불리우며 그의 제자로 워렌 버핏(Warren Buffet)이 아직도 활동 중이다.
