---
title: "A Change of the MultiPillar OldAge Income Security System"
description: |
  다층 연금 구조, 석사 3학기 퇴직연금강의 기말과제
author:
  - name: sonsungman
    url: https://sonsungman.github.io/SKKU-Preditive.m
date: 06-07-2021
output:
  distill::distill_article
---


## 다층연금체계의 현황과 문제점에 대해서 논하시오


### 1

우리나라의 다층연금체계는 기본적으로 0층 기초연금, 1층 국민연금, 2층 퇴직연금, 3층 개인연금(사적연금)의 구조를 가지고 있다. 다양한 지점에서 문제점이 지적되고 있는데 몇 가지 문제점들을 꼽아보자면 1. 각 제도 간 역할과 기능이 연계되어 있지 않다는 점 2. 국민연금 납부비율, 소득유지 기능 약화가 진행되고 있다는 점 3. 퇴직연금의 경우 일부 정규직 근로자 중심으로 운영되며 대부분의 근로자가 퇴직연금제도를 의미 있는 노후소득보장 수단으로 인식하고 있지 않다는 점 4. 개인연금제도의 경우 중산층 이상의 소득계층 중심으로 가입이 이루어지고 있으며, 노후소득보장 수단 보다는 세제혜택을 위한 역할에 그치고 있는 점들을 꼽을 수 있다. 이러한 문제점들을 해결하기위해 다양한 논의가 계속되고 있다. 모든 나라의 연금 개혁의 두 가지 목표는 급여적정성(adequacy)와 지속가능성(sustainability)이다. 다만, 이 둘의 목표는 서로 상충되기에 결국 연금 개혁안은 두 목표를 조화 혹은 절충하는 작업이다. 이 두가지 목표 하에서 제기된 문제점들에 대한 해결책을 모색해야 한다. 

### 2

먼저, 연금 개혁 이전에 연금 정보의 폭넓은 전달 강화가 필요하다는 점을 꼽고 싶다. 무엇보다도 중요한 지점은 연금 수요자들에게 자신의 미래 연금 소득 수준이 어떻게 변화할 수 있는지, 현재 자신이 납부하고 있는 보험료의 수준은 어떻게 산정되고 있는지, 자신의 생애 혹은 상황에 맞추어서 자신의 연금 생활을 선택할 수 있는 폭을 넓이기 위해 자신이 현재 속해 있는 연금제도에 관한 다양한 정보를 얻을 수 있도록 해야 한다. 이를 위해선 가장 먼저 연금 계층간 역할과 기능이 연계되고 이를 함께 논의하고 포괄할 수 있는 조직이 필요하다고 생각한다. 즉, 국민연금 따로, 퇴직연금 따로 기초연금 따로 개인연금 따로 운영 주체에 따라 각각의 정보만은 수요자에게 전달하는 수준에서 머무는 것이 아니라, 각 계층에 수요자가 교집합으로 속할 테니 각각의 제도가 이러한 수요자 맞춤 정보를 함께 제공할 수 있는 체계를 갖추는 것이 필요하다고 생각한다. 

### 3

두번째로 공적 연금과 사적 연금 간의 역할 분담의 명확화가 필요하다고 생각한다. 사적 연금의 경우 우리나라에서 대부분 중산층 이상이 가입하고 있으며 사적 연금이 국민 전체 개인의 노후 소득 보장에 큰 역할을 담당하고 있지 않고 그저, 세제혜택을 위한 도구로서 사용되고 있다는 점은 안타까운 현실이다. 그렇기에 영국의 사례처럼 공적연금은 빈곤층을 위한 제도로서 사용되고 사적연금 제도를 강화하여 대부분의 국민들이 사적연금제도를 통해 실질적인 노후 보장을 진행하는 것이 연금 개혁의 적절한 방향으로 생각된다. 무엇보다 기초연금의 경우는 대상이 65세 이상 국민 전체를 목표로 하고 재정 방식이 부과방식으로서 당해 세대에 재정 책임이 있기에 사적연금의 강화는 필히 이러한 기초연금의 재정 방식에 대한 변화를 가지고 올 수 있을 것이다. 즉, 사적 연금의 강화는 필히 개인의 연금 조성에 대한 시각을 바꾸며 개인이 자신의 노후 보장을 위해 사적 연금 재정을 꾸려 나가야하기 때문에 이러한 부분이 기초연금 뿐 아니라 국민연금에 대한 재정 부담도 줄일 수 있는 요인이 될 것이다. 국민연금의 경우 재정방식이 부분적립방식으로서 부분사전적립하고 나머지는 미래세대에 재정 책임을 이연하는 효과가 발생하므로 세대간의 갈등이라는 오래된 주제는 점점 줄어들 수 있다. 또한 국민연금이 갖는 소득 보장 기능의 하락과 재정에 대한 끊임없는 부담은 범 정부적인 차원에서 국가안의 문제로서 존재하므로 사적 연금 제도의 강화는 국민연금에 대한 여러가지 문제점들을 또한 완화시키는 요인으로 작용할 것이다.

### 4

물론 각 제도가 가지고 있는 고유의 문제점들이 모두 존재한다. 하지만 이러한 문제점들은 점진적인 연금 개혁을 통해 해소될 수 있다고 본다. 문재인 정부는 연금제도와 공적 보험에 있어서 범 정부적 차원의 공적 제도 역할 강화를 이어왔다. 하지만 이부분은 단순히 정치적 논제로서 다루어져야 할 것이 아닌 현실적인 실현 가능한 대안으로서 미래의 국민들의 노후소득보장의 청사진이 되어야 한다. 즉, 공적 연금강화는 물론 현재의 상황과 정치적 환경을 고려한 조치이지만 이는 점차적으로 사적 연금강화라는 방향으로 옮겨가야만 한다고 생각한다. 국가가 국민 모두의 노후를 보장해 주어야 한다는 주장의 의미는 단순히 정치적 주장이 아니라 경제적 현실적 결함을 갖는다고 생각한다. 국민연금 재정방식에는 사적연금의 오랜 보험료 산출 원리인 수지 상등의 원칙이 적용되지 않는다. 이는 우리에게 많은 시사점을 준다고 생각한다. 80년대와 90년대 고도의 성장기를 거쳐왔던 시기엔 대한민국의 미래 성장 가능성에 힘입어 충분히 국민연금의 재정방식에 대한 부담이 없었다고 본다. 하지만 성장세가 점점 꺽여가는 고도화된 대한민국의 현실에서는 현재의 국민연금 재정방식이 갖는 문제점은 분명하다. 그렇기에 제도적으로 공적연금의 기능은 현재 기초연금이 갖는 기능으로 축소하고 더불어 빈곤층에 대한 보호를 공적연금이 할 수 있는 방향으로 진행하며 사적연금 제도의 강화를 통해 대다수의 국민들이 노후를 보장해가는 체계의 마련이 필요하다고 생각한다. 사적연금의 강화는 현재 보험회사들의 역할 강화와 맞물린다. 보험 본래의 기능과 실제 보험회사에서 보험료가 산출되는 구조를 본다면 전적으로 공평하며 각각의 계약자 개인이 갖는 위험을 진단하여 보험료를 산출하기에 개인의 노후 보장뿐 아니라 기관 투자의 역할 강화로서 국가적 차원의 투자 재원 마련으로 국가 경제에 이바지할 수 있다고 본다. 미시적으로 본다면 단순히 개인의 노후 보장을 개인에게 맡기는 것으로서 보일 수 있지만 결과적으로 이 기금을 운용하고 위험을 분류하여 보험료를 책정하는 보험회사의 관점에서 보면 개인의 이러한 노후에 관한 경제적 리스크는 대수의 법칙을 통해 분산된다. 즉, 사적 연금 강화가 개인의 노후를 개인에게만 맡기는 무책임한 의미가 아닌 개인이 갖는 위험을 적절히 평가하여 그 위험에 맞는 공정한 보험료를 책정하고 이를 비슷한 위험을 갖는 계약자간 위험을 분산시키는 의미로 볼 수 있다. 국민연금이 갖는 투자 운용에서의 이점은 분명히 존재한다. 이러한 점을 고려해본다면 독일의 실손보험제도와 비슷하게 보험회사들의 언더라이팅 기능과 보험료 부과 기능은 살리면서 국민들의 노후보장을 위한 연금 기금에 대한 운용은 국민연금과 같은 국가적 차원에서 투자 운용을 해가는 것이 필요하다고 본다. 이러한 구조로의 변화 혹은 개혁은 현재 국민연금이 갖는 미래 세대에 대한 재정 책임 이연에 대한 문제를 해결할 수 있다. 기초연금의 경우 국가 차원의 복지 제도로서 생각한다면 충분히 용인될 수 있고 퇴직연금 또한 사용자와 노동자가 함께 부담하며 근로자의 노동 소득에 맞추어 설계되어 있어 용인될 수 있지만 국민연금의 경우 필히 갈등을 가지고 올 수 밖에 없는 구조라 생각한다. 그러므로 국민연금의 역할에 대한 점진적인 개혁이 국가 차원 다층연금제도 개혁에 가장 중요한 부분을 차지할 것이다 생각한다. 

### 5

한편, 코로나 사태 이후 주식시장에 동학 개미로 불리우는 많은 개인 투자자의 유입이 있었고 이러한 움직임이 금융 문맹 퇴치와 이어지고 또한 개인의 노후보장에 대한 인식 환기로서 작용하는 부분이 있다고 생각한다. 개인의 노후가 개인의 책임이다 라는 주장은 복지국가로서 대한민국에는 어울리지 않아 보인다. 하지만 개인의 노후가 개인의 준비를 필요로 한다는 지점은 모두들 동의할 것이다. 이러한 개인의 노후 준비에 있어서 가장 중심적인 부분을 차지할 것이 바로 다층연금제도일 것이다. 그렇기에 다층연금제도 자체에 개인이 자신 노후를 준비할 수 있는 선택의 폭이 필요하며 이는 단순히 공적 연금이 노후를 보장해 준다는 정치적 논의를 넘어서 실제적이고 경제적이며 현실적인 준비로서 사적연금제도의 강화가 이를 도와줄 수 있다고 본다. 또한, 앞서 제안한 연금 정보 통합 조직의 구축은 이러한 연금 개혁의 중추적 과제로서 사적연금제도 강화와 함께 진행되어야 할 것이다.
