---
title: "석사과정의 마무리"
description: |
  보험계리학
author:
  - name: sonsungman
    url: https://sonsungman.github.io/SKKU-Preditive.m/
date: 12-12-2021
output:
  distill::distill_article
---

### 서론

석사과정의 마무리를 눈앞에 두고 있다. 2019년도 말에 생명보험사 구직에 실패하고 인턴을 할지 대학원에 진학할지 고민을 했었다. 보험계리학 자체에 관심이 있었기에 국내의 석사과정 진학을 하게 되었고 4학기동안 많은 것들을 배웠다. 함께 공부했던 분들을 생각하면 각자가 목표를 가지고 오셨던 것 같다. 자격증 취득을 하고 이를 발판으로 취업을 하고자 하는 분. 직장에서 대학원에 보내주어 쉬러 오셨다는 분. 무엇을 하러 왔는지 모르겠는 분. 논문 면제를 통해 3학기 만에 빠르게 원하는 직장에 취업을 한 분 등등. 나의 목표는 무엇이엇을까 생각한다면 처음엔 한국시험을 마무리 해야겠다는 생각도 있었지만 공부를 하다보니 보험계리학 전반에 걸친 다양한 논문들을 접해볼 수 있었다는 것이다. 그리고 이를 바탕으로 석사학위논문을 작성하고 본심사를 통과했다. 한국자격증의 경우 취득에 별 미련이 없기에 미국자격증을 취업 후에 1년 반 정도를 들여서 마무리 하고자 한다. 보험계리학 전반에 걸친 다양한 지식들을 습득했기에 솔직히 미국자격증의 경우 시간만 들이면 충분히 취득할 수 있어보인다. 필기 시험의 경우 1과목 정도 남았고 온라인 모듈이 2개 R을 활용한 시험 PA가 하나 남아서 예상컨데 30살 정도에는 취득할 수 있지 않을까라는 예상은 하고 있다. ASA과정인데 그 이후에 FSA를 취득할지는 그때 가서 고민해야 할듯 헌데 FSA 트랙자체가 3~4개의 시험을 패스해야하고 준수한 영어 실력이 필요하기 때문이다. 석사학위논문 주제 자체도 FSA GI트랙의 한 꼭지로 썻다. 초고 쓰는데 까지 6개월 걸렸으니 보통 시험하나 패스하는데 1년정도 잡고 공부를 해야하는 것으로 보인다. 

### 삶에 태도에 관하여

대학원에서 다양한 가치관의 대립을 보았다. 대학원 무용론과 스스로 계속해서 싸워야 했다. 왜 나는 대학원에 와서 이렇게 고생을 하는가? 팀플을 할때에도 팀원 분들께 별 의욕을 느낄 수 없었다. 그저 적당히 하자. 넘어가자라는 느낌... 비난의 여지는 전혀 없다. 그 모든 것이 각자의 인생  플랜 안에서 돌아가는 것이니,,, 나같은 경우는 4학기 수업을 충실히 수강했다라고 자신한다. 

### 리더십에 대하여

대학원에서 리더십에 대해서 배울 수 있었다고 생각한다. 회사생활에서 필요한 리더십은 뭘까라는 고민을 많이 했었다. 계리학 공부를 하면서도 결과적으로 취업을 하여 실무에 뛰어들 터이니, 다양한 팀프로젝트를 하면서 나름 고민을 했엇는데 결과적으로 내가 내린 결론은 윗 사람께 잘하고 후배분들 개기는 거 잘 다독이며 일이 성사되도록 잘 이끄는 것이다. 이게 참 어렵다. 나 스스로 열심히만 한다고 되는게 아니다. 손해볼 각오를 해야한다. 그래야지 사람들이 따라온다. 성인이 되서 사회에서 만나게 되면 각자 손해 안 보고 소위 호구 안되겠다고 열심히들 눈치를 보는 것 같다. 맞는데, 리더십의 부재가 참으로 안타깝다고 생각한다. 누구는 리더병이라고 하던데 이러한 생각을 가지신 분께는 이렇게 대답해 주고 싶다. 한번 사시는 인생인데 비참하게 그저 톱니바퀴가 되어 살 것인지 자신이 함께 일하는 동료와 부하직원, 윗사람께 좋은 영향을 끼치며 성과를 내고 자신이 속한 조직과 사회를 발전시키며 갈 것인지... 인생에 대한 가치관이고 동기부여 측면이다. 일에 대해 돈만 보고 뛰어들게 된다며 분명 한계가 존재한다. 의미, 성장, 가치에 대해서 얘기하지 않으며 우리는 정체된다. 분명하게 정체된다. 연습이고 훈련이다. 어디를 가던지 계속해서 나를 가꿔가야한다. 안락함에 취하여 자신을 방치하지 말라. 새로운 동기부여, 새로운 도전. 새로운 의미가 필요한 시점이다. 

### 졸업

취업을 해야하는데 쉽지 않다. 한국시험이 2018년도 부터 2022년도 까지 각 과목 합격률 50%를 유지하기 위해 소위 쉬워지면서 계리사 공부를 하시는 많은 분들이 유입되었다. 한편 취업 시장 각 재보사,원수사, 공제회, 은행 등과 로컬, 글로벌 컨설팅사 들의 TO가 이를 모두 다 흡수하지 못하는 실정이다. 많이 못 미친다. 또한 계리사 자격증을 통해 소위 법적인 업무영역을 보장받는 것이 아니다. 즉, 계리사 자격증이 없어도 업무하는데에는 크게 문제가 없다는 것이다. 대학원에서 상품관련 엑셀 시트를 가지고 1학기 수업을 진행 하였을 때에도 또한 프로펫 소프트웨어를 사용하였을 때에도 계리학을 전공했다고 한들 큰 의미가 없다라는게 내 결론이 었다. 시험 공부를 통해 전반적인 내용을 학습하고 실무에서 소프트웨어 활용역량 키워서 업무에 투입되면 큰 문제가 없어보인다. FSA 트랙의 지식이라는 것도 실무를 하면서 취득하도록 과정이 설계되어있다. 즉, 계리학은 실무를 바탕으로 발전했다. 개인적으로 이러한 이유때문에 한국계리사 시험을 준비하다가 미국계리사시험으로 전향한 부분이 있다. 한국 시험의 경우 각 트랙에 대해 깊이 있게 배우지는 못한다. 물론 어려운 시험이지만 예를 들어 연금 분야의 전문가가 되겠다라는 생각을 가진 학생이라면 한국보험계리사 시험의 연금수리학 과목을 수험용 서적과 함께 준비하여 합격 한다고 해서 전문가가 되는 것이 아니라는 의미다. 가성비를 원한다면 한국보험계리사, 깊이를 원하며 사서 고생하겠다라는 사람들은 SOA를 취득해야한다고 생각한다.

### 결론

이 글을 마지막으로 이 홈페이지에 더 이상의 업로드는 없을 것이다. 내 대학원 2년이 고스란히 남겨져 있는 아카이브로서의 역할을 하는 곳이고 나의 삶에 있어 27-28에 무엇을 했는지 생각날 때마다 이 홈페이지를 찾아와 다시 볼 목적으로 만든 것이다. 물론 자기소개서에 홈페이지를 기입하여 내가 했던 포트폴리오를 보여주는 목적도 있기는 했다. 어찌보면 장님이 코끼리 다리를 더듬는 듯한 과정의 연속이었다. 한 외국계 생보사 면접 때에 나에게 현업에 계시는 선배분 없으시냐라고 면접관께서 물은 기억이 난다. 공부를 해가며 몇 분을 알게 되었지만 이 질문의 의미는 나에게 뭐하러 이렇게 사서 고생했느냐, 취업이 목적이 었으면 분명 빠른 길이 있었을 텐데 너가 정보가 부족해서 그런 것이 아니었느냐라는 질문으로 느껴졌다. 반은 맞고 반은 틀린다라고 생각이 들었다. 앞서서 얘기했지만 대기업에 취업하는 것이 과연 인생의 목표가 될 수 있는가라는 고민을 해봐야한다라고 생각한다. 계리를 하고 싶어 온 것이지 대기업에서 높은 연봉을 받는 것이 나의 목표는 아니다. 허울보단 일을 쫒아야한다. 로컬, 글로벌 컨설팅사 혹은 원수사, 재보사 등등 보험업계 전반적으로 계리적 지식이 사용되는 어디는 상관은 없다. 내가 쌓아왔던 지식들에  실무적 경험들을 더하고 싶을 뿐이다. 이론적으로는 기회가 된다면 FSA가 되고 싶다. 한편 석사학위논문 전자파일 등재를 마쳤다. 통과되고 인쇄하여 교수님들 싸인 받고 제출하면 끝난다. 2월정도에 RISS 내이름 검색하면 나온다. 손성만 검색해보길 ㅋㅋ

### 교훈

보험계리와 리스크에 대해서 학습하면서 궁극적으로 얻은 교훈 : 정보비대칭성은 궁극적으로 시스템리스크를 유발하며 시스템의 붕괴는 사람들의 피를 먹고 복구된다. 그러니 정보비대칭을 제거하는 역할과 책임이 몹시 중요하다.
