---
title: "IAD part 2"
description: |
  From Lecture, Insurance Accounting and Discount rate
author:
  - name: sonsungman
    url: https://sonsungman.github.io/SKKU-Preditive.m
date: 04-26-2021
output:
  distill::distill_article

---

### 전체적 구조: IAA의 Discount rate 모노그래프를 통한 할인률의 이해


###교재 Ⅵ-26 Term Effects (기간 효과) ~

특정 시점에 수익률 곡선의 기간구조를 지정하는 방법은 여러 가지 있다. 이 모노그래프에서는 현물이자율과 선도이자율이라는 두 가지 접근방식에 초점을 맞춘다. 
Spot Curve를 만드는 목적은 쿠폰의 수준이나 만기 든 상관없이 할인할 수 있는 능력을 갖추기 위해서이다. 앞서 설명된 YTM의 문제는 쿠폰 타입이나 만기에 의존하는 이자율 이였다. 그렇기에 할인율로서 적절치 않다. YTM은 특정 채권의 내부수익률을 나타내는 정보에 불과하다. 범용성이 부족하다. 채권상품구조를 바꾸면 할인율로서 사용될 수 없다. 

벨류에이션은 원하는 현금흐름을 적절이 할인하여 현재가치로 만드는 작업이다. 그때에 쓰일 수 있는 할인율을 결정할 때에 Yield Curve가 등장한다. 
〖(1+i(t))〗^t  principal 여기에서 i(t)가 연간 현물이자율에 해당한다. 수익률곡선의 미래 움직임을 결정하기위해 여러가지 모형들이 사용되고 대표적으로 Vasiceck model, hull-white model, Cox-Ingersoll-Ross model 등이 있다. 이러한 모델들은 차익 기회를 피하도록 조정된다. 미래의 시점에 사용될 현물이자율 곡선을 만들어내는데 이러한 모델들이 사용된다. 컬리브레이션은 시장가격과 이론가격을 갖게 만들어주기 위해 모수를 맞추어 주는 작업이다. Vasiceck과 CIR 모델과 Hull-white 모델은 다르다. Hull-white 모델은 기본적으로 무이표채권에 대해서 이론가격과 시장관찰 가격이 일관되게 만들어내는 모델이다. 그렇기에 Hull-White 모델은 Arbitrage Free 모델이라고 한다. 기초자산의 가격을 일치시키거나- (Vasiceck, CIR), Hull-White 모델의 경우 파생상품의 가격 일치를 통해 컬리브레이션한다.

수익률 곡선의 형태(shape)를 설명하는 데에 일반적으로 인용되는 세가지 이론이 있다. 시장세분화이론, 시장기대이론, 비유동성프리미엄 이론. 

시장세분화 이론이란 예를 들어 짧은 듀레이션의 자산은 트레이더들에게 어필될 것이고 긴 듀레이션의 자산은 연기금이나 생명보험회사들에게 어필될 것이다. 즉, 듀레이션 기간에 따라 자산의 시장은 서로 분리되어 독립적으로 작용하며 각각의 수익률은 투자자들의 선호에 따라 결정된다는 이론이다. 

시장 기대 이론이란 투자자들이 평균적으로 기대하는 미래이자율을 반영하는 것이 채권수익률의 기간구조라는 주장이다.

비유동성 프리미엄이론이란 투자자들이 유동성을 선호하여 만기가 긴 채권일수록 장기간 투자하는 대가로 기대 단기 이자율 외에 추가적인 프리미엄을 요구한다고 주장하는 이론이다. 비유동성 프리미엄과 유동성 프리미엄은 동일한 의미이다. 

비유동성 프리미엄이론은 비유동성 프리미엄과 수익률 곡선의 형태 사이에 가능한 연관성이 있음을 제안한다. 이 점은 Amihubd 가 제기하는데 이는 미국재무부(장기)채권 수익률에도 비유동성프리미엄이 존재함을 보여준다. 단기 채권은 장기 채권보다 더 유동적일 수 있으며, 이는 시간경과에 따라 상승하는 수익률 곡선을 야기할 것이다. 

유동성 프리미엄은 항상 양(+)의 값이며 만기가 증가하면서 증가하기 때문에, 유동성 프리미엄이론에 의해서 제시되는 수익률 곡선은 항상 기대 이론에 의해서 제시되는 수익률 곡선보다 위에 더 급한 기울기를 지닌다.

수익률 곡선에 영향을 줄 수 있는 또 다른 요인으로는 정치적 요인들, 양적 양화(QE)등이 있다. 먼저, 정치적 요인으로는 영국과 미국의 중앙은행들의 시중은행에 대한 대출 금리를 들 수 있다. 서브프라임 모지기 사태 이후 영국의 기준 금리와 미국의 목표 연방기금금리는 굉장히 낮은 수준을 유지하고 있다. (옮긴이 - 이 책이 발간된 시점을 고려해야한다.) 양적 양화는 또 다른 정치적 요인들이라고 볼 수 있다. 중앙은행의 통화공급량 증가를 위해 자산을 매입하는 과정에서 자산 매입은 해당 자산의 수익률에 직접적인 영향을 미칠 것이다. 예를 들면 QE에 의해 수요가 증가하므로 채권 가격이 상승하고 이로서 채권의 액면 가격은 그대로 인해 채권 가격의 상승으로 수익률은 감소한다. 이는 결국 수익률 곡선의 감소를 가지고 올 수 있다. 실증의 예로서 2010년 2월 10일에 영국 은행은 금융위기에 대한 반작용으로서 200B에 해당하는 자산을 매입했다. 대부분의 자산 구성은 국채였고 영국은행 연구소는 이러한 QE가 약 1%가량의 국채 수익률을 낮추었다고 지적했다. 

위의 논의의 대부분은 명목 할인율, 즉 인플레이션에 대한 조정이 없는 할인율에 초점을 맞추고 있다. 실질 수익률 곡선이 더 적절한 경우가 존재한다. 대표적인 예로 인플레이션 조정 연금부채를 평가할 때이다. 인플레이션에 대한 더 깊은 논의는 Discount Rate in Financial Reporting (2013)의 10장 Inflation을 참고하기 바란다. (계속)


