---
title: "ALM"
description: |
  ALM에 대하여 
author:
  - name: sonsungman
    url: https://sonsungman.github.io/SKKU-Preditive.m
date: 03-08-2021
output:
  distill::distill_article

---


### Introduction


보험업은 다른 산업과 달리 리스크기반의 자본집약적 산업이다. 개인이나 기업이 갖는 리스크를 인수(Underwriting)하여 해당 리스크에 관한 보장을 제공한다. 그 중 생명 보험은 크게 3가지 영역에 대한 보장을 제공한다. 질병, 장해, 사망에 따른 보장 (보장성 상품), 미래 큰 지출을 위한 보장 (저축 및 자산 적립 상품), 퇴직 후 안정적인 소득 보장 (연금 또는 적립금 인출 상품). 한편, 손해보험은 광범위한 리스크에 대한 보장을 제공하는데 재물보험, 농작물보험, 홍수보험, 주택보험, 해상보험, 항공보험, 자동차보험, 의료사고배상책임보험 등 다양한 리스크를 보장하는 보험 상품을 제공한다. 보험회사는 보험계약자의 미래 손실을 보장해 주는 대가로 보험료를 받는다. 그리고 보험계약에 따른 보장의무는 곧바로 이행되지 않는 미래의 불특정한 시점의 의무이기에 부채로서 보험회사의 B/S에 나타난다. 

미리 받은 보험료는 미래의 보장의무를 이행하기위한 재원으로서 사용되지만 보험료 납입 시점과 보험사고 발생 시점사이의 차이는 보상의무를 고려한 적절한 보험료 재원의 투자를 요구한다. 결국, 보험회사는 보험료를 바탕으로 투자한 자산의 현금흐름과 인수한 보험계약의 보장의무를 나타내는 보험부채의 현금흐름 사이에서 회사 가치(순자산가치)와 수익을 최대화해야 하는 상황에 놓여 있다. 

Asset-liability management (ALM)은 보험회사 혹은 금융기관(은행 또한 같은 상황에 놓인다.)가 이러한 문제를 풀기위해 사용하는 접근법이다. 이제 ALM을 구체적으로 알아보도록 하자.


### 1


1980년대 초반 미국의 상호생명보험회사 Equitable은 10년까지 16% 이자율 보증을 제공하는 보험상품을 다수 팔았다. 이자율 보증을 충당하기위해 단기 이자율에 투자하였는데 단기 이자율의 붕괴로 장기의 높은 이자율 보증 수준을 커버하기엔 부족하여 회사에 위기가 닥쳐왔고 결국 Equitable은 탈상호화 하였고 Axa 그룹에 인수되었다. 이 사례를 통해 이후 많은 금융 회사의 매니저들은 견고한 ALM 체계를 만드는데 집중하였다. 


### 2


ALM은 금융기관이 자금 중개 기능을 하면서 발생할 수 있는 자산의 현금흐름과 부채의 현금흐름 사이의 불일치를 방지하기 위해 금리 리스크 뿐만 아니라 유동성 리스크(Liquidity risk) 관리를 목표로 개발되었다. ALM측면에서 보험회사는 보유한 자산과 부채가 노출된 리스크(Risk)의 성격과 자산과 부채사이의 관계에 대해 높은 수준의 이해가 요구된다. 보험부채는 상품설계에서부터 달라지기에 ALM에 있어서 보험회사는 상품 설계과정에서부터 마케팅, 경영전략, 자산 배분, 보험회사의 지급여력에 따른 요구자본까지도 고려해야 한다.


### 3


보험회사가 판매하는 상품의 특징에 따라 보험부채가 노출되는 Risk가 달라진다. 생명보험 상품의 경우 보험 기간이 장기로서 이자율의 변동에 따라 부채가 크게 변동하고 미래 현금흐름의 불확실성이 증가한다. 즉, 부채가 금리 리스크에 많이 노출된다.

또한 생명보험상품이 갖는 보증옵션의 성격에 따라서도 다양한 리스크에 노출된다. 한편, 보험 기간이 단기이거나 갱신형인 손해보험상품의 경우 해당 보험부채는 금리 리스크에 적게 노출될 수 있지만 같은 손해보험인 경우에도 의료사고배상책임보험와 같은 상품은 클레임이 종결할 때까지 오랜 기간(long tail claims)이 걸리는데 이에 해당하는 부채는 필히 금리 리스크에 많이 노출된다. 그리고 자산에 있어서 보상액을 지급하기위해 보험회사는 채권이나 주식, 부동산 등의 자산에 투자하게 되는데 보험회사의 투자 포트폴리오에서 큰 규모에 해당하는 채권의 경우 가치가 금리의 변동에 따라 변동하기에 금리 리스크에 크게 노출된다. 


### 4


보험회사는 미래에 지속적으로 발생할 보험금 등의 지급의무(부채)를 자산의 현금흐름으로 충족시켜야 한다. 정확한 현금흐름의 매칭은 현실적으로 어려움이 따르기에 그 대안으로서 이자율 변화로부터 포트폴리오의 가치를 보호하는 면역화 전략을 이용할 수 있다. 1952년 영국의 보험계리사 Frank Redington은 자산이 아래 조건을 만족시키도록 함으로써 이자율 변동에 대해서 비즈니스 포트폴리오가 어떻게 면역화되는지 보여주었다. 

-	시장 이자율 하에서 자산의 현재가치가 부채의 현재가치가 같을 경우

-	자산 수정듀레이션(변동성)과 부채 수정듀레이션(변동성)이 같을 경우

-	듀레이션 근처에서 부채의 컨벡시티가 자산의 컨벡시티보다 작을 경우


특정 이자율 수준에서 면역화가 달성되고 나면 이자율이 다소 변하더라도 이론적으로는 자산과 부채 포트폴리오의 매칭이 대체로 유지되어야 한다. 그러나 시간이 흐르고 이자율 수준이 더욱 변하면 새로운 이자율 수준하에서는 면역화가 무너질 수 있기에 포트폴리오 리밸런싱이 필요하다. 레딩톤 면역화는 이자율의 변동이 작을 경우에만 유효하며 가정에 따른 한계점들이 존재한다.
