---
title: "실손의료보험의 역유지 현상과 해약률 실증분석 논문 번역 "
description: |
  번역 완료 제출.
author:
  - name: sonsungman
    url: https://sonsungman.github.io/SKKU-Preditive.m
date: 09-26-2021
output:
  distill::distill_article
---

### 1. 초록

실손의료보험 시장은 급격한 성장기를 지나 성숙단계로 진입하고 있다. 또한 국민 건강보험의 보장범위 확대, 손해율의 구조적 상승과 같은 체계적 위협에 직면하고 있다. 이에 계약자 특성 및 상품 특성이 해약률에 미치는 영향을 분석하고 실손의료보험 시장의 역유지(adverse retention) 현상과 문제점을 살펴보았다. 실제 실손의료보험 계약자료와 청구자료를 사용해 현재 요율변수, 선택담보, 보험금 청구실적, 경과기간과 해약률에 대한 일반화선형모형 분석결과, 여성, 연령 증가, 보험금 청구자, 경과년수 증가, 낮은 상해급수일수록 해약을 적게 하는 것으로 나타났다. 특히 저위험군에 해당하는 보험금 비청구자(non-claimant)군과 고위험에 해당하는 보험금 청구자(claimant)군의 해약률 격차가 현저했는데, 이는 실손의료보험 시장의 역선택이 가입 단계에서만 나타나는 것이 아니라 해약 단계에서도 존재한다는 점을 시사한다. 역유지는 저위험군 탈퇴, 고위험군 유지의 계약자 이동을 야기하며 장기적으로 반복될 경우 가입 역선택과 마찬가지로 가입자 구성(policyholder mix)을 변동시켜 구조적 보험료 상승의 원인이 된다. 따라서 실손의료보험의 안정성을 위해 저위험군 비청구자 (no-claim) 가입자군의 계약유지 유인을 높이기 위한 제도적 고심이 필요해 보인다.

The Korean private health insurance market is currently moving in to the early mature stage and facing the systemic changes such as the structural premium hike due to aging population and the possibility of expanding coverages of national health insurance, which probably will constitute the exact substitutes. In this work, we analyze the impact of policyholder and product characteristics such as age, gender, level of injury, claimant and contract age on lapse in the Korean private health insurance industry using individual contracts data with generalized linear models(GLMs). We find that all considered policyholder and product characteristics have a statistically significant impact on the lapse rate, but the magnitude of the effects varies. Empirical results also show that the lapse tends to be low among the female, the elderly, the claimant, the old contract and the regular income earner. Also, we note that there is predominant difference of lapse rates between the claimant and the non-claimant, implying adverse retention, the other adverse selection at decrement. Adverse retention could trigger unfavorable policyholder dynamics: the more risker the less lapse and the less risker the more lapse, making the policyholder mix gravely undesirable. In conclusion, we suggest that the regulatory review to provide the low risk the incentive to retain their contracts be considered.

### 2. purpose of the study

이 연구는 실손의료보험의 계약자 특성 및 상품 특성이 해약률에 미치는 영향에 대한 실증분석이다. 사용된 자료는 실손의료보험 계약자료와 청구자료이며 방법론은 일반화선형모형이다. 본고는 그 동안 자료의 제약성으로 제한적으로 다루어졌던 실손의료보험의 계약자 특성과 해약률에 대한 면밀한 검토와 현 국면에서 실손의료보험 시장의 문제점 제기에 초점을 맞추고자 하였다.
   실제 실손의료보험이 해약과 계약자 특성을 파악하는데 도움이 될 수 있을 것이며 다음과 같은 점에서 본 연구는 시의 적절성을 갖는다.
   첫째, 실손의료보험이 성숙시장에 진입함에 따라 현 시점에서 실손의료보험 시장의 제도적 미비점을 규명하고 개선함으로써 기존 가입자의 제도 이탈을 낮추고 계약유지를 장기화할 수 있는 방안을 마련하는 것이 더 시급해 보인다.
   둘쨰, 계약자 특성과 계약자 이동에 대한 분석결과는 실손의료보험의 제도적 안정성에 대한 재고가 필요함을 보여준다. 분석결과, 보험금 청구이력이 있는 가입자와 청구이력이 없는 가입자간 해약률 차이가 현저하였다. 이러한 현상을 역유지라 하는데 역유지는 가입단계뿐만 아니라 해약단계에서도 역선택이 발생하는 것으로 다기간에 걸쳐 반복될 경우 제도 존속에 위협요인이 될 수 있다.
   해약률엔 관한 연구는 설명변수에 따라 구분된다. 하나는 Kuo, Tsai, Chen(2003)처럼 이자율, 실업률, 등 거시변수와 해약률간의 관계를 분석하는 것으로 이들은 긴급자금가설과 이자율가설을 검증하였다. 다른 하나는 개별 계약자료를 이용해 계약자 특성과 해약률간의 관계를 분석하는 것으로 Li, Jensen(2012) 은 2000~2008년 HRS자료를 이용하여 미국 장기요양보험(LTCI)의 해역률을 분석하였다. Eling, Kiesenbauer (2013)는 2000~2010년 기간의 생명보험 계약자료를 이용해 해약률에 영향을 미치는 상품유형 및 계약자 특성을 분석하였다. Christiansen, Eling, Schmidt, Zirkelbach (2014)는 2010년의 민영의료보험 계약자료를 이용해 상품유형 및 계약자 특성이 해약률에 미치는 영향을 분석하였다.
   해약률에 대한 국내 선행연구로는 황진태, 이경희(2010)가 2000~2008년 보험개발원 자료를 이용해 추정한 월별, 년간 생명보험 상품군별 해지율이 있다. 추정 결과, 계약 유지기간이 상대적으로 긴 연금을 제외한 나머지 상품군의 해지율이 가입 후 6~9개월까지 급격히 상승하다가 이후 완만하게 감소하는 것으로 드러났다. 민영의료보험 해약률 연구로는 유창훈, 김정동(2011)과 김대환(2016)이 있는데 모두 의료패널자료를 이용하였다. 전자는 민영의료보험 가입 결정요인과 해약 결정요인을 동시에 다루었기 때문에 해약에 대해서는 개인별 특성에 대한 단변량 분석만을 제시하였다. 김대환 역시 2008~2013년 의료패널을 사용해 실손의료보험 해약을 분석했다. 병원 방문과 보험금, 장애, 만성질환 등을 대리변수로 하여 건강상태가 좋지 않을 경우 계약을 유지하는 경향이 있고 반대의 경우에는 해약을 하는 사후적 역선택을 발견하였다.

   This study is an empirical analysis of the effect of policyholder and product characteristics of PHI on the lapse rate. The data used are PHI contract data and claim data, and the methodology is a generalized linear model. This paper attempted to focus on a close review of the policyholder characteristics and lapse rate of PHI, which have been limited to data constraints, and raising problems in the PHI market in the current situation.    
   Actual PHI can help identify lapse and policyholder characteristics, and this study has timeliness in the following points.
   First, as PHI enters the mature market, it seems more urgent to come up with measures to reduce existing policyholder’ departure from the system and prolong contract retention by identifying and improving institutional deficiencies in the PHI market at this point. Second, the analysis results of policyholder characteristics and policyholder movement show that it is necessary to reconsider the institutional stability of PHI. As a result of the analysis, the difference in lapse rate between policyholders with a history of claim and policyholders without a history of claim was remarkable. This phenomenon is called Adverse Retention, and Adverse Retention is the occurrence of Adverse Selection not only in the taking out stage but also in the lapse stage, and if repeated over a period of time, it can be a threat to the continuation of the system.
   Studies on lapse rate are classified according to explanatory variables. One is to analyze the relationship between macro variables such as interest rate, unemployment rate, and lapse rate, such as Kuo, Tsai, and Chen (2003), and they verified the emergency fund hypothesis and interest rate hypothesis. The other is to analyze the relationship between policyholder characteristics and lapse rate using individual contract data, and Li and Jensen (2012) analyzed the lapse rate of US Long-Term Care Insurance (LTCI) using HRS data from 2000-2008. Eling and Kiesenbauer (2013) analyzed the product types and policyholder characteristics that affect the lapse rate using life insurance contract data for the period 2000-2010. Christiansen, Elling, Schmidt, and Zirkelbach (2014) analyzed the effect of product types and policyholder characteristics on lapse rate using private medical insurance contract data from 2010. Previous domestic studies on the lapse rate include monthly and annual lapse rate estimated by Hwang Jin-tae and Lee Kyung-hee (2010) using data from the Korea Insurance Development Institute from 2000 to 2008. As a result of the estimation, it was found that the lapse rate of the rest of the product group rose sharply from six to nine months after taking out, except for pensions with a relatively long contract persistency period, and then gradually decreased. Research on the lapse rate of private medical insurance includes Yoo Chang-hoon, Kim Jung-dong (2011), and Kim Dae-hwan (2016), all of which used medical panel data. Since the former dealt with both the determinants of private medical insurance signing up and the determinants of lapse, only a univariate analysis of individual characteristics was presented for lapse. Kim Dae-hwan also analyzed the lapse of PHI using the 2008-2013 medical panel. Hospital visits, insurance benefit, disability, and chronic diseases were used as proxy variables, and the contract tended to be maintained when the health condition was poor, and in the opposite case, a post adverse selection was found. 

### 3. theoretical frameworks

#### Table 1

분석에 사용된 자료는 실제 실손의료보험의 계약자료와 청구자료이다. 설명변수의 자료집계기간은 2012년부터 2015년까지 4기간이며 종속변수인 해약은 2016년 보험료 납입실적을 기준으로 유지와 해약을 구분하였다. 설명 변수는 요율변수인 성별, 연령, 상해등급, 계약자 선택담보, 경과기간이다.

The data used for the analysis are actual contract data and claim data of PHI. The data aggregation period for explanatory variables is four periods from 2012 to 2015, and lapse, a dependent variable, was classified into persistency and lapse based on the 2016 premium payment performance. Explanatory variables are rate variables such as gender, age, level of injury, chosen coverage, and contract age.

#### Table 2

실손의료보험 가입자가 선택할 수 있는 최소담보단위는 상해외래(injury-outpatient), 상해입원(injury-inpatient), 질병외래(disease-outpatient), 질병입원(disease-inpatient)이다. 가입자는 네 가지 최소담보 중에서 선택할 수 있으며 선택한 담보수에 따라 계약자별 세부보장이 달라진다

The minimum coverage unit that PHI policyholder can choose are injury-outpatient, injury-inpatient, disease-outpatient, and disease-inpatient. Policyholders can choose from four minimum coverage, and detailed coverage for each contractor vary depending on the number of coverages selected. 

#### Table 3

계약자 구성은 남성이 54.9%로 여성 45.1%보다 약 10% 많았고 직업군에 따라 분류되는 상해등급은 사무직인 1급이 61.5%, 2급과 3급이 38.5%이다.

The mix of policyholders was 54.9% for men, about 10% more than 45.1% for women, and 61.5% for first-class office workers and 38.5% for second-class and third-class workers.

#### Table 4

<Table 4>는 전체 가입자(policyholder), 가입자 중 보험금 비청구자 (non-claimant), 가입자 중 보험금 청구자(claimant) 세 그룹의 선택담보 별 가입비율이다.

<Table 4> is the subscription ratio for each of the three groups of policyholders, non-claimants among policyholders, and claimants among policyholders.

#### Table 5

<Table 5>는 청구자 그룹과 비청구자 그룹의 계약유지 및 해약을 정리한 비율 분할표이다. 가로는 청구자/비청구자간 구성비율이고 세로는 계약유지/탈퇴간 구성비율이다.

<Table 5> is a ratio division table that summarizes the retention and lapse of contracts between the claimant group and the non-claimer group. Horizontal is the composition ratio between the claimant and the non- claimant, and vertical is the composition ratio between retention and decrement of the contract.

#### Table 6

<Table 6>의 담보별 해약률은 청구자/비청구자의 선택담보별 탈퇴계약 비율이다. 

The lapse rate by coverage in <Table 6> is the ratio of decrement contracts by chosen coverages of the claimant/non- claimant.

#### Table 7

<Table 7>은 빈도와 심도에 따른 담보별 속성을 보여준다. 비청구자 그룹의 해약률이 청구자 그룹의 해약률 보다 컸던 것처럼 청구자 내 유지계약의 빈도와 심도가 해지계약의 빈도와 심도 보다 크다.

<Table 7> shows the properties of each coverage according to frequency and severity. Just as the lapse rate of the non- claimant group was greater than that of the claimant group, the frequency and severity of the retention contract within the claimant are greater than the frequency and depth of the decrement contract.

#### Table 8

<Table 8>은 현재 그룹별 해약률이 유지된다고 단순 가정했을 때 5기간 후 유지율이다. 다른 모든 조건이 동일하고 계약자 구성의 변화만 반영했을 때 보험료는 현재 수준대비 15.9%이 증가한다. 저위험군의 해약률이 고위험군의 해약률보다 큰 지금의 상태가 일정 기간 지속되는 것만으로도 계약자 구성은 변하고 보험료 인상 역시 불가피해진다.

<Table 8> is the retention rate after 5 periods assuming that the current lapse rate for each group is maintained. When all other conditions are the same and only changes in the mix of policyholders are reflected, insurance premiums increase by 15.9% compared to the current level. As the current state, where the lapse rate of the low-risk group is greater than that of the high-risk group, continues for a certain period of time, the mix of policyholders changes and premium increase becomes inevitable. 

#### Model

실증분석에 사용된 반응변수 y_i는 해약발생에 대한 지시변수로 0과 1의 값을 가지며 베르누이 분포를 따른다. 일반화선형모형은 반응변수의 기댓값 μ_i의 로짓 함수값 g(μ)=lna(μ/(1-μ))는 예측결과값 x'β를 [0,1]으로 변환해주므로 해약과 같이 0혹은 1의 값을 갖는 이진형 반응변수에 적합하다.

The response variable y_i used in the empirical analysis has values of 0 and 1 as indicators for the occurrence of lapse and follows the Bernoulli distribution. The generalized linear model is suitable for binary response variables with a value of 0 or 1 such as lapse because the logit function value g(μ)=lna(μ/(1-μ)) of expectation value μ_i of the response variable converts the predicted result value x'β into [0,1]. 

### 4. Analysis

#### Table 9

요율변수 중 이탈도 감소는 상해등급 3,270, 성별 1,601, 연령 357 순이다. 상해등급은 양이 추정계수값을 가지며 등급이 올라갈수록 해약이 증가하는 것으로 나타났다. 앞서 살펴보았듯이 C[5]상해의 해약률은 비청구자, 청구자 그룹 모두 평균대비 높았고 빈도도 평균보다 낮았다. 

Among the rate variables, the decrease in deviance is in the order of the level of injury  3,270, gender 1,601, and age 357. It was found that the level of injury had a positive estimation coefficient, and the higher the level, the higher the lapse. As discussed earlier, the lapse rate of C[5] injury was higher than the average for both non- claimant and claimant groups, and the frequency was lower than the average.

#### Table 10

성별의 경우 남성보다는 여성이 해약을 덜 하는 것으로 나타났다. 여성의 오즈값은 e^0.9로 30대 남녀의 해약률 차이는 0.8%이고 60대 남녀의 해약률 차이는 0.6%이다.

In the case of gender, women were found to have less lapse than men. The odds value of a woman is e^0.9. The difference in lapse rate between men and women in their 30s is 0.8%, and the difference in lapse rate between men and women in their 60s is 0.6%.

#### Table 11

경과년수 추가로 인한 이탈도 감소는 89,031로 설명변수 중 가장 높았다. 오즈값은 0.3으로 보유기간이 늘어남에 따라 해약률이 감소하는 것으로 나타났다. 이는 일반적으로 해약률은 초년도 해약률이 가장 높고 시간이 지남에 따라 감소하는 경향과 일치한다. <Figure 2>는 경과년수별 실제 해약률로 2년도 해약률이 13.8%로 가장 높다.

The decrease in deviance due to the addition of the coverage age was 89,031, the highest among explanatory variables. The odds value was 0.3, indicating that the lapse rate decreased as the retention period increased. This is generally consistent with the tendency of the lapse rate to be the highest in the initial year and to decrease over time. <Figure 2> is the actual lapse rate by the coverage age, and the two-year lapse rate is the highest at 13.8%.

#### Table 12

청구실적 변수(비청구자/청구자)의 오즈값은 0.3으로 청구실적이 있을 경우 비청구자에 비해 해약을 덜 하는 것으로 나타났다. 해약률은 기본집단(남자, 30대, 상해1급) 기준으로 비청구자 10.3%, 청구자 3.3%로 추정되었다. 성별차이가 가장 적은 연령대는 60대 0.2%로 다른 연령대의 성별차이 0.3%보다 낮았다.

The odds value of the claim performance variable (non-claimant/ claimant) was 0.3, indicating that if there was a claim history, the lapse was less than that of the non-claimant. The lapse rate was estimated to be 10.3% for non-claimants and 3.3% for claimants based on the basic group (men, 30s, first-class injury). The age group with the smallest gender difference was 0.2% in their 60s, lower than the gender difference of 0.3% in other age groups.

#### Figure 4

<Figure 4>은 비청구자 그룹을 좀 더 세분해서 살펴보고자 분석자료의 무청구년수별 해약률을 나타낸 것이다. 경과기간 4년인 계약은 전체 계약의 19.2%로 경과기간 4년 계약만을 대상으로 집계한 해약률이다.

<Figure 4> shows the lapse rate by number of non-claimed years of analysis data in order to further subdivide the non-claimant group. Contracts with a four-year coverage age are 19.2% of the total contracts, which are the lapse rate for contracts with only four-year coverage age.

#### Table 14

세부담보 모형의 기준수준은 C[15]전체 담보이다. 설명변수 추가로 인한 이탈도 감소는 8,465로 다른 설명변수에 비해 가장 적었다. 담보변수 중 일부에 대해서는 유의하지 않은 결과가 나타났다. 이는 C[15]전부선택, C[5]상해, C[6]외래, C[9]입원, C[10]질병 이외에 담보를 선택한 가입자 비율이 2%로 자료의 수가 작기 때문인 것으로 보인다. 또한 유의한 결과가 나온 일부 담보 역시 기준수준에 비해 해약률 상대도가 지나치게 높게 나타나 담보에 따라 해약 정도를 단순비교하기에는 어려워 보였다.

The reference level of the detailed coverage model is C[15] total coverage. The decrease in diviance due to the addition of explanatory variables was 8,465, the lowest compared to other explanatory variables. There were insignificant results for some of the coverage variables. This seems to be due to the small number of data, with 2% of policyholders choosing coverage without all C[15] choices, C[5] injuries, C[6] outpatient, C[9] inpatient, and C[10] disease. In addition, some coverage with significant results also showed too high relative lapse rate compared to the standard level, making it difficult to simply compare the degree of lapse depending on the coverage.

#### Table 15

C[6]외래와 C[10]질병의 오즈값은 0.55, 0.89로 기본수준인 C[15]전체 담보에 비해 낮았고, C[5]상해와 C[9]입원의 오즈값은 1.80, 1.61로 전체 담보에 높았다. 상해와 입원은 질병과 외래에 비해 상대적으로 빈도는 낮고 심도가 높은 편으로 심도가 클수록 해약률이 높다고 할 수 있다.

The odds values of C[6] outpatient and C[10] diseases were 0.55, 0.89, which was lower than the basic C[15] total coverage, and the odds values of C[5] injury and C[9] inpatient were 1.80 and 1.61, which were high for the total coverage. Injury and inpatients are relatively less frequent and higher in severity than diseases and outpatients, and the higher the severity, the higher the lapse rate.

#### Table 16

<Table 16>은 각 분석모형의 적합성 평가지표와 적합성 검정의 결과이다. 요율변수(성별, 나이, 상해등급)과 선택담보, 청구이력 여부, 경과기간 중 가 장 많은 이탈도 감소를 보인 설명변수는 경과년수이다. 또한 요율변수와 두 변수 조합 중 가장 큰 이탈도 감소를 보인 것은 선택담보와 경과년수이다.

<Table 16> is the suitability evaluation index and the result of suitability test of each analysis model. Among the explanatory variables such as rate variables (gender, age, level of injury), chosen coverage, claim history, and coverage age, the variable that showed the most decrease in deviance is the coverage age. In addition, the largest decrease in the deviance between the combination of the rate variables and the two variables was chosen coverage and coverage age.

#### Table 17

교호항에 대해서 가장 설명력이 높은 경과기간을 중심으로 검토한 결과 경과기간과 이탈도감소의 경우와 마찬가지로 경과기간과 선택담보 교호항의 설명력이 가장 높은 것으로 나타났다. 다른 변수들에 대해서 교호항을 적용한 결과는 원래 모형과의 차이가 크지 않았다.

As a result of reviewing the interaction term focusing on the most explanatory coverage age, the explanatory power of the coverage age and the interaction term for chosen coverage was found to be the highest as in the case of coverage age and a decrease of deviance. As a result of applying the interaction term to other variables, the difference from the original model was not significant.

#### Table 18

모든 설명변수 모형에서도 여성, 연령 증가, 청구자, 경과년수 증가, 낮은 상해등급일수록 해약률이 낮아 개별모형과 일관된 결과를 나타냈다. 다만 담보별 해약의 경우 선택담보 모형에서는 상해와 입원이 전체담보보다 해약이 낮았다. 모든 변수를 포함한 모형에서는 상해, 입원, 질병, 외래 모두 전체담보 대비 해약률이 높아 개별모형의 결과가 더 신뢰성이 높다고 생각한다.

In all explanatory variable models, women, age increase, claimant, coverage age, and lower level of injury showed lower lapse rate, consistent results with individual models. However, in the case of lapse by coverage, injuries and inpatient were lower than the total coverage in the chosen coverage model. In the model including all variables, injury, inpatient, disease, and outpatient all have a high lapse rate compared to the total coverage, so we think the results of the individual model are more reliable.

### 5. Results

이 연구는 실제 실손의료보험 계약자료와 청구자료를 이용한 실증분석을 통해 실손의료보험의 계약자 특성과 선택담보별 특성이 해약률에 미치는 영향을 다루었다. 분석을 통해 검토한 실손의료보험의 특징들은 다음과 같다. 첫째, 계약자별⋅상품별 특성이 해약률에 미치는 영향을 확인하였다. 성 별, 연령, 상해등급, 경과년수, 보험금 청구실적, 선택담보가 설명변수로 사 용되었으며 현재 요율변수와 각각의 설명변수에 대한 추정식에서 모두 통계 적으로 유의미한 결과를 나타내었다. 둘째, 계약자별⋅상품별 특성에 대한 개괄적 사항의 기술과 요약을 포함하였다. 자료의 제약성 등으로 제한적으로 검토되었던 사항들에 대해 분석 취지를 넘어서지 않는 한도 내에서 가급적 많은 정보를 전달하고자 하였다. 특히 세분화된 선택담보별 정보는 실손의료보험의 위험특성에 대한 이해도 제고에 유용할 것이다. 셋째, 역유지(adverse retention) 현상을 확인하고 야기될 수 있는 문제점을 검토하였다. 청구자와 비청구자 그룹간 해약률 차이는 실손의료보험의 역유지를 강하게 시사하며 현 상태가 지속되는 것만으로 불리한 계약자 구 성이 야기될 수 있다는 점을 환기해주었다. 무엇보다 무청구년수가 증가할 수록 해약률이 증가한 점은 저위험 고객군의 제도이탈 방지 방안의 정립 필 요성을 강하게 뒷받침하였다. 현재 실손의료보험은 2017년 이후 신규 가입자에 대해서 무청구 시 보험 료의 일부를 할인하도록 하고 있다. 이는 저위험군 가입자의 유인 제공의 필 요성에 대해서 감독당국도 숙지하고 있다는 뜻으로 해석된다. 하지만 이는 계약자간 위험정도를 청구자와 비청구자로 구분한 것으로 아주 제한적인 계 약자실적의 반영이다. 실제 계약자간 위험수준별 분포와는 상당한 차이가 있으며 청구자 집단 내의 잔여 위험특성 편차 역시 매우 크다22). 세분화되 지 못한 위험집단의 구분은 위험평가의 정교함을 개선하는데 제한적일 수밖에 없다. 만일 할인할증제도처럼 계약자실적 정보를 좀 더 포괄적으로 반영할 수 있다면 보다 정교한 위험수준별 보험료 부과가 가능할 수 있다. 끝으로 분석에 사용된 자료는 실손의료보험이 특약으로 가입이 가능하였 던 시기의 자료이므로 주계약의 특성에 따라 해약이 발생할 여지가 존재할 수 있으므로 차후에 실손의료보험이 단독상품으로 팔린 자료에 대한 추후 연구가 필요하다.

This study dealt with the effect of policyholder and coverage characteristics of PHI on the lapse rate through empirical analysis using actual PHI contract data and claim data. The characteristics of PHI reviewed through analysis are as follows. First, the effect of the characteristics of each policyholder and product on the lapse rate was confirmed. Gender, age, level of injury, claimant and contract age, and coverage were used as explanatory variables, and statistically significant results were shown in both the current rate variables and the estimation equation for each explanatory variable. Second, it included a summary and description of general information on the characteristics of each policyholder and product. We tried to deliver as much information as possible to the extent that it did not exceed the purpose of analysis on matters that had been limitedly reviewed due to data constraints. In particular, the detailed information by coverage will be useful in enhancing the understanding of the risk characteristics of PHI. Third, we identified the inverse retention phenomenon and reviewed problems that may be caused by this. The difference in lapse rate between the claimant and non-claimer groups strongly suggested the adverse retention of PHI and recalled that the continued current status could lead to unfavorable policyholder mix. Above all, the fact that the lapse rate increased as the number of non-claimed years increased strongly supported the need to establish a plan to prevent the departure of low-risk policyholder. Currently, PHI has allowed new policyholder to be discounted part of their insurance premiums if they do not claim since 2017. This is interpreted as meaning that regulators are well-acquainted with the need to provide incentives for low-risk policyholders. However, this is a reflection of very limited policyholder claim, as the level of risk between policyholders is divided into claimant and non-claimant. There is a significant difference from the distribution by risk level among actual policyholders, and the deviation in residual risk characteristics within the claimant group is also very large. The classification of unsegmented risk groups is bound to be limited in improving the sophistication of risk assessment. If policyholder claim information can be more comprehensively reflected, such as the Bonus-Malus system, more sophisticated premium charging by risk level may be possible. Finally, the data used for the analysis are data from the time when PHI was available as a special contract, so there may be room for lapse depending on the characteristics of the main contract, so further research is needed on the data sold as a single product in the future.

### 6. Refernce

Kim, Daehwan, “Empirical Analysis of Maintaining and Canceling Behaviors of the Indemnity Private Health Insurance and Its Implications,” Korean Journal of Insurance 108 (2016): 29-54.

You, Changhoon and Kim, Jeongdong, “A Study on the Determinants of Purchasing and Surrendering Private Health Insurance,” Journal of Risk Management 22(2) (2011): 189-222.

Lee, Kyoungah and Lee, Hangsuck, “Adverse Selection and Rates Differentiation in the Korean Private Health Insurance,” Journal of Risk Management 27(3) (2016): 93-128.

Lee, Hangsuck, Lee, Gaeun and Lee, Kyoungah, “A Ratemaking of the Korean Private Health Insurance using GLM,” Journal of Risk Management 28(7) (2017): 37-71.

Lee, Hangsuck, Lee, Minha and Baek, Hye-Yeon, "An Empirical Analysis of Bonus-Malus System in the Private Health Insurance," Korean Journal of Insurance 111 (2017): 41-73.

Lee, Hangsuck, Lee, Su-Bin and Baek, Hye-Yeon, "Rate Differentiation in the Korea Private Health Insurance," Korean Journal of Insurance 111 (2017): 41-73.

Hwang, Jintae and Lee, Kyounghee, “Estimating and Forecasting Models of Lapse Rates in the Life Insurance Industry,” KiRi Research Report (2010)

Altman, Daniel, David M. Cutler, and Richard J Zeckhauser, “Adverse Selection and Adverse Retention,” American Economic Review 88(2) (1998): 122-126.

Christiansen, Marcus, Martin Eling, Jan-Philipp Schmidt and Lorenz Zirkelbach, “Who is Chaing Health 

Insurance CoverageEmpirical Evidence on Policyholder Dynamics,” The Journal of Risk and Insurance 83(2) (2014).

Eling, Martin and Dieter Kiesenbauer, “What Policy Features Determine Life Insurance Lapse? An Analysis of the German Market,” The Journal of Risk and Insurance 81 (2013): 241-269.

Faraway, J. Julian, Extending the Linear Model with R, CRC Press, 2016.

Jong, De Piet and Gillian Z. Heller, Generalized Linear Models for Insurance Data, Cambridge, 2008.

Kuo, Weiyu, Chenghsien Tsai and Wei-Kuang Chen, “An Empirical Study on the Laps Rate: The Cointegration Approach,” The Journal of Risk and Insurance 70 (2003): 489-508.

Li, Yong and Gail A. Jensen, “Why Do People Let Their Long-term Care Insurance Lapse? Evidence from the Health and Retirement Study,” Applied Economic Perspectives and Policy 37(2) (2012): 220-237.

Financial Supervisory Service (http://www.fss.or.kr)

GENERAL INSURANCE ASSOCIATION OF KOREA (https://kpub.knia.or.kr)

Statistics Korea (http://kostat.go.kr)


