---
title: "Hedging"
description: |
  헷징에 대하여 
author:
  - name: sonsungman
    url: https://sonsungman.github.io/SKKU-Preditive.m
date: 03-08-2021
output:
  distill::distill_article
---

### Introduction



생명보험회사는 미래 불특정한 시점에 발생할 보험사고에 따라 약속한 보험금을 계약자에게 지불해야하는 의무를 갖는다. 그 의무는 보험회사의 재무상태표(B/S)상 책임준비금이라는 이름의 부채로 나타난다. 특히, 적립금의 투자의사결정(주식에 투자할지, 채권에 투자할지 등)을 계약자가 선택하는 변액 보험의 경우 보험회사는 최저보증옵션(GMXB)를 제공하는데 최저보증옵션 이란 예를 들어 적립금의 투자수익률이 최저보증(4%)이하로 떨어지더라도 4%의 투자수익률을 보험회사가 보장해주는 옵션을 말한다. (그 외에도 여러가지의 옵션이 존재한다.) 이러한 최저보증옵션의 제공을 위해 보험회사는 보증준비금이라는 부채를 적립한다. 

적립금이 주식에 투자되었을 경우 주가가 하락하면 보증 준비금으로 인해 보험회사의 부채는 크게 감소하지 않지만 자산의 규모는 줄어 들어 자본이 잠식되는 문제가 발생될 수 있다. 이때 파생상품 투자를 통해 주가 하락 시 파생상품 손익이 발생하여 자산의 감소가 크지 않다면 자본 감소가 발생하지 않을 것이다. 이와 같이 파생상품을 활용하여 주가나 금리 하락 시 자본 감소를 방지하는 것이 헷지의 기능이다. 이번 장에서는 이러한 보험회사 헷지의 기본이 되는 콜 옵션과 풋 옵션의 관계인 풋콜 패리티 식을 알아보고 이를 이용한 간단한 전략을 살펴본다.


### 1


풋콜 패리티 식은 아래와 같이 구성된다.

Call-Put=PV(forward price-strike price)
 
유럽형 옵션을 기준으로 같은 행사가와 만기를 갖는다면 콜옵션과 풋옵션 가격의 차이는 같은 만기를 갖는 포워드의 가격(Forward price)과 행사가(Strike price)의 차이의 현재 가치(PV)와 같다는 의미다.

변액 상품을 구매한 계약자가 특정 주식에 적립금을 모두 투자하기로 결정했다고 가정해보자. 미래 주가 하락은 계약자의 적립금 감소를 가져오며 보험회사 자산의 감소가 발생한다. 이러한 자산의 감소를 방어할 수 있는 전략으로 보호적 풋전략을 생각해 볼 수 있다. 앞서 계약자가 투자한 특정 주식을 기초자산으로 하는 풋 옵션을 매입하게 되면 미래 주가하락에 대한 손실을 풋 옵션 행사를 통해 풋 옵션의 프리미엄만큼만 고정할 수 있어 보험회사 자산의 감소를 방어할 수 있다.


### 2
 

헷지에 사용하기 위해 원하는 콜 옵션 혹은 풋 옵션이 없을 때에는 풋콜 패리티 식을 활용하면 해당 파생상품과 동일한 현금흐름을 복제할 수 있다.  


Put=Call-PV(forward price-strike price)
Put=Call+ PV(strike price)-PV(forward price)


위 식을 해석해보면 동일 조건의 Call 옵션을 매입하고 PV(Strike Price) 만큼 무위험 채권에 투자하며 선불선도계약(Prepaid forward)을 매도포지션(short)에서 맺는다면 풋옵션의 현금흐름을 복제할 수 있다는 의미이다.


### 3


파생상품 거래 시장엔 원하는 기초자산과 만기를 갖는 거래상품이 많지 않기 때문에 보호적 풋 전략(기초 자산 매입 + 풋 매입) 또한 파생상품 매입을 하지 않고 같은 효과를 가지고 올 복제 전략이 필요하다. 그러므로 복제 전략에 해당하는 동적 자산배분 전략(dynamic asset allocation strategy)를 간단하게 소개하겠다.풋 옵션의 블랙숄즈 공식을 변형해보자.

$$
P=Xe^{-rt} N(-d_2 )-SN(-d_1)
$$
$$
P+S=Xe^{-rt} N(-d_2 )-SN(-d_1 )+S
$$
$$
P+S=Xe^{-rt} N(-d_2 )+S(1-N(-d_1 ))
$$
$$
P+S=Xe^{-rt} N(-d_2 )+S(N(d_1 ))
$$
가장 아래 식을 해석해보면 좌변은 보호적 풋 전략(기초 자산 매입 + 풋 매입)으로 이해할 수 있다. 우변의 앞은 무위험채권에 대한 투자, 뒤는 주식 매입을 의미한다. 정리하면 보호적 풋 전략은 주식과 무위험 채권의 매입으로 구성된 포트폴리오에서 두 자산의 편입비율을 적절히 조절함으로써 결합할 수 있다.
