---
title: "지급여력제도와 예금보험료의 조화"
description: |
  보험학회하계학술대회
author:
  - name: sonsungman
    url: https://sonsungman.github.io/SKKU-Preditive.m
date: 08-20-2021
output:
  distill::distill_article
---


2021년 8월 20일 금요일 한국보험학회와 한국리스크관리학회, 한국보험계리사회 등 공동 주관으로 하계연합 학술대회가 열렸다. 이항석 교수님께서는 보험계리 세션 사회자로서 참여하시고 또한 발표자로서 “지급여력제도와 예금보험료의 조화”라는 주제로 발표하셨다.

이 날 발표는 예금보험료의 계산에 관한 주제로 진행되었다. 예금보험제도란 보험회사의 파산 시 자산보다 부채가 많아져 일부 계약자에게 보험금을 지급하지 못할 경우에 파산한 보험회사 대신 예금보험제도를 통해 일부 지급이 이루어지게 하는 제도이다. 보험회사는 예금보험공사에 예금보험료를 납입하고 예금보험공사는 보험회사 지급불능 시 일부 계약자들에게 지급을 해주는 구조이다.

이항석 교수님께서는 “보험회사가 리스크를 적절히 관리하면 재무적 지급불능 상황에 빠질 가능성이 낮아지므로 두가지 제도(지급여력제도, 예금보험제도)가 유기적으로 조화를 이루어야 한다는 측면에서 연구를 시작하게 되었다”고 말씀하셨다.

예금보험료에 관한 기존의 연구는 부채의 만기가 정해져 특정 시점에 (만기 시점) 지급불능 상황이 발생한다고 가정하거나 자산과 부채의 모델에 jumps를 도입하지 못하였다. 이 두가지 문제점을 보완하여 자산과 부채의 모델에 jumps를 도입하고 early exercise가 가능하도록 한 부분에서 본 연구의 차별점이 있다고 설명하셨다.

본 발표에서 흥미로운 지점은 자산과 부채의 상관계수ρ 가 커질수록 보험회사의 ALM 수준이 높다고 가정할 때 ρ의 크기가 증가할 수록 실제 국내 보험사의 데이터를 활용한 예금보험료율이 작아지고 자산 부채 비율을 증가시켰을 때에도 예금보험료율의 감소를 확인할 수 있었다는 것이다. 또한 부채의 jump size가 커질수록 예금보험료율이 상승하는 것도 확인할 수 있었다. 이러한 수치분석을 통해 보험회사로 하여금 예금보험료를 줄이기 위해 그들의 ALM수준과 재무구조 향상에 대한 인센티브를 제공한다고 결론을 내리며 발표는 마무리되었다.
